/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class ACstGrammar extends PCstGrammar
{
    private TLitInt _litInt_;

    public ACstGrammar()
    {
        // Constructor
    }

    public ACstGrammar(
        @SuppressWarnings("hiding") TLitInt _litInt_)
    {
        // Constructor
        setLitInt(_litInt_);

    }

    @Override
    public Object clone()
    {
        return new ACstGrammar(
            cloneNode(this._litInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACstGrammar(this);
    }

    public TLitInt getLitInt()
    {
        return this._litInt_;
    }

    public void setLitInt(TLitInt node)
    {
        if(this._litInt_ != null)
        {
            this._litInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._litInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._litInt_ == child)
        {
            this._litInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._litInt_ == oldChild)
        {
            setLitInt((TLitInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
