/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TAmpCaretEq extends Token
{
    public TAmpCaretEq()
    {
        super.setText("&^=");
    }

    public TAmpCaretEq(int line, int pos)
    {
        super.setText("&^=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAmpCaretEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAmpCaretEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAmpCaretEq text.");
    }
}
