/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TAppend extends Token
{
    public TAppend()
    {
        super.setText("append");
    }

    public TAppend(int line, int pos)
    {
        super.setText("append");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAppend(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAppend(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAppend text.");
    }
}
