/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TCaretEq extends Token
{
    public TCaretEq()
    {
        super.setText("^=");
    }

    public TCaretEq(int line, int pos)
    {
        super.setText("^=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCaretEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCaretEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCaretEq text.");
    }
}
