/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TChan extends Token
{
    public TChan()
    {
        super.setText("chan");
    }

    public TChan(int line, int pos)
    {
        super.setText("chan");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TChan(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTChan(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TChan text.");
    }
}
