/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TFloat64 extends Token
{
    public TFloat64()
    {
        super.setText("float64");
    }

    public TFloat64(int line, int pos)
    {
        super.setText("float64");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFloat64(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFloat64(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFloat64 text.");
    }
}
