/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TGo extends Token
{
    public TGo()
    {
        super.setText("go");
    }

    public TGo(int line, int pos)
    {
        super.setText("go");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGo text.");
    }
}
