/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TMinusEq extends Token
{
    public TMinusEq()
    {
        super.setText("-=");
    }

    public TMinusEq(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMinusEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMinusEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMinusEq text.");
    }
}
