/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TPercentEq extends Token
{
    public TPercentEq()
    {
        super.setText("%=");
    }

    public TPercentEq(int line, int pos)
    {
        super.setText("%=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPercentEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPercentEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPercentEq text.");
    }
}
