/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TPipeEq extends Token
{
    public TPipeEq()
    {
        super.setText("|=");
    }

    public TPipeEq(int line, int pos)
    {
        super.setText("|=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPipeEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPipeEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPipeEq text.");
    }
}
