/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TRune extends Token
{
    public TRune()
    {
        super.setText("rune");
    }

    public TRune(int line, int pos)
    {
        super.setText("rune");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRune(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRune(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRune text.");
    }
}
