/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TSlashEq extends Token
{
    public TSlashEq()
    {
        super.setText("/=");
    }

    public TSlashEq(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSlashEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSlashEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSlashEq text.");
    }
}
