/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TStarEq extends Token
{
    public TStarEq()
    {
        super.setText("*=");
    }

    public TStarEq(int line, int pos)
    {
        super.setText("*=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStarEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStarEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStarEq text.");
    }
}
