/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.parser;

import golite.node.*;
import golite.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTImport(@SuppressWarnings("unused") TImport node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPackage(@SuppressWarnings("unused") TPackage node)
    {
        this.index = 1;
    }

    @Override
    public void caseTChan(@SuppressWarnings("unused") TChan node)
    {
        this.index = 2;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDefault(@SuppressWarnings("unused") TDefault node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDefer(@SuppressWarnings("unused") TDefer node)
    {
        this.index = 5;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 6;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 7;
    }

    @Override
    public void caseTStruct(@SuppressWarnings("unused") TStruct node)
    {
        this.index = 8;
    }

    @Override
    public void caseTInterface(@SuppressWarnings("unused") TInterface node)
    {
        this.index = 9;
    }

    @Override
    public void caseTFunc(@SuppressWarnings("unused") TFunc node)
    {
        this.index = 10;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 11;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 12;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 13;
    }

    @Override
    public void caseTSwitch(@SuppressWarnings("unused") TSwitch node)
    {
        this.index = 14;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 15;
    }

    @Override
    public void caseTGoto(@SuppressWarnings("unused") TGoto node)
    {
        this.index = 16;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 17;
    }

    @Override
    public void caseTBreak(@SuppressWarnings("unused") TBreak node)
    {
        this.index = 18;
    }

    @Override
    public void caseTContinue(@SuppressWarnings("unused") TContinue node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFallthrough(@SuppressWarnings("unused") TFallthrough node)
    {
        this.index = 20;
    }

    @Override
    public void caseTGo(@SuppressWarnings("unused") TGo node)
    {
        this.index = 21;
    }

    @Override
    public void caseTMap(@SuppressWarnings("unused") TMap node)
    {
        this.index = 22;
    }

    @Override
    public void caseTRange(@SuppressWarnings("unused") TRange node)
    {
        this.index = 23;
    }

    @Override
    public void caseTSelect(@SuppressWarnings("unused") TSelect node)
    {
        this.index = 24;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 25;
    }

    @Override
    public void caseTAppend(@SuppressWarnings("unused") TAppend node)
    {
        this.index = 26;
    }

    @Override
    public void caseTPrintln(@SuppressWarnings("unused") TPrintln node)
    {
        this.index = 27;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 28;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 29;
    }

    @Override
    public void caseTFloat64(@SuppressWarnings("unused") TFloat64 node)
    {
        this.index = 30;
    }

    @Override
    public void caseTRune(@SuppressWarnings("unused") TRune node)
    {
        this.index = 31;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 32;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 33;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 34;
    }

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 35;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 36;
    }

    @Override
    public void caseTPercent(@SuppressWarnings("unused") TPercent node)
    {
        this.index = 37;
    }

    @Override
    public void caseTAmp(@SuppressWarnings("unused") TAmp node)
    {
        this.index = 38;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 39;
    }

    @Override
    public void caseTCaret(@SuppressWarnings("unused") TCaret node)
    {
        this.index = 40;
    }

    @Override
    public void caseTLshift(@SuppressWarnings("unused") TLshift node)
    {
        this.index = 41;
    }

    @Override
    public void caseTRshift(@SuppressWarnings("unused") TRshift node)
    {
        this.index = 42;
    }

    @Override
    public void caseTAmpCaret(@SuppressWarnings("unused") TAmpCaret node)
    {
        this.index = 43;
    }

    @Override
    public void caseTPlusEq(@SuppressWarnings("unused") TPlusEq node)
    {
        this.index = 44;
    }

    @Override
    public void caseTMinusEq(@SuppressWarnings("unused") TMinusEq node)
    {
        this.index = 45;
    }

    @Override
    public void caseTStarEq(@SuppressWarnings("unused") TStarEq node)
    {
        this.index = 46;
    }

    @Override
    public void caseTSlashEq(@SuppressWarnings("unused") TSlashEq node)
    {
        this.index = 47;
    }

    @Override
    public void caseTPercentEq(@SuppressWarnings("unused") TPercentEq node)
    {
        this.index = 48;
    }

    @Override
    public void caseTAmpEq(@SuppressWarnings("unused") TAmpEq node)
    {
        this.index = 49;
    }

    @Override
    public void caseTPipeEq(@SuppressWarnings("unused") TPipeEq node)
    {
        this.index = 50;
    }

    @Override
    public void caseTCaretEq(@SuppressWarnings("unused") TCaretEq node)
    {
        this.index = 51;
    }

    @Override
    public void caseTLshiftEq(@SuppressWarnings("unused") TLshiftEq node)
    {
        this.index = 52;
    }

    @Override
    public void caseTRshiftEq(@SuppressWarnings("unused") TRshiftEq node)
    {
        this.index = 53;
    }

    @Override
    public void caseTAmpCaretEq(@SuppressWarnings("unused") TAmpCaretEq node)
    {
        this.index = 54;
    }

    @Override
    public void caseTAmpAmp(@SuppressWarnings("unused") TAmpAmp node)
    {
        this.index = 55;
    }

    @Override
    public void caseTBarBar(@SuppressWarnings("unused") TBarBar node)
    {
        this.index = 56;
    }

    @Override
    public void caseTLarrow(@SuppressWarnings("unused") TLarrow node)
    {
        this.index = 57;
    }

    @Override
    public void caseTPlusPlus(@SuppressWarnings("unused") TPlusPlus node)
    {
        this.index = 58;
    }

    @Override
    public void caseTMinusMinus(@SuppressWarnings("unused") TMinusMinus node)
    {
        this.index = 59;
    }

    @Override
    public void caseTEqEq(@SuppressWarnings("unused") TEqEq node)
    {
        this.index = 60;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 61;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 62;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 63;
    }

    @Override
    public void caseTExclamation(@SuppressWarnings("unused") TExclamation node)
    {
        this.index = 64;
    }

    @Override
    public void caseTNotEq(@SuppressWarnings("unused") TNotEq node)
    {
        this.index = 65;
    }

    @Override
    public void caseTLtEq(@SuppressWarnings("unused") TLtEq node)
    {
        this.index = 66;
    }

    @Override
    public void caseTGtEq(@SuppressWarnings("unused") TGtEq node)
    {
        this.index = 67;
    }

    @Override
    public void caseTColonEq(@SuppressWarnings("unused") TColonEq node)
    {
        this.index = 68;
    }

    @Override
    public void caseTElipsis(@SuppressWarnings("unused") TElipsis node)
    {
        this.index = 69;
    }

    @Override
    public void caseTParenL(@SuppressWarnings("unused") TParenL node)
    {
        this.index = 70;
    }

    @Override
    public void caseTParenR(@SuppressWarnings("unused") TParenR node)
    {
        this.index = 71;
    }

    @Override
    public void caseTSquareL(@SuppressWarnings("unused") TSquareL node)
    {
        this.index = 72;
    }

    @Override
    public void caseTSquareR(@SuppressWarnings("unused") TSquareR node)
    {
        this.index = 73;
    }

    @Override
    public void caseTBraceL(@SuppressWarnings("unused") TBraceL node)
    {
        this.index = 74;
    }

    @Override
    public void caseTBraceR(@SuppressWarnings("unused") TBraceR node)
    {
        this.index = 75;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 76;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 77;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 78;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 79;
    }

    @Override
    public void caseTLitInt(@SuppressWarnings("unused") TLitInt node)
    {
        this.index = 80;
    }

    @Override
    public void caseTLitOctal(@SuppressWarnings("unused") TLitOctal node)
    {
        this.index = 81;
    }

    @Override
    public void caseTLitHex(@SuppressWarnings("unused") TLitHex node)
    {
        this.index = 82;
    }

    @Override
    public void caseTLitFloat(@SuppressWarnings("unused") TLitFloat node)
    {
        this.index = 83;
    }

    @Override
    public void caseTLitRune(@SuppressWarnings("unused") TLitRune node)
    {
        this.index = 84;
    }

    @Override
    public void caseTLitRaw(@SuppressWarnings("unused") TLitRaw node)
    {
        this.index = 85;
    }

    @Override
    public void caseTLitInterpreted(@SuppressWarnings("unused") TLitInterpreted node)
    {
        this.index = 86;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 87;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 88;
    }
}
