/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.analysis;

import java.util.*;
import golite.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPCstGrammar().apply(this);
        outStart(node);
    }

    public void inACstGrammar(ACstGrammar node)
    {
        defaultIn(node);
    }

    public void outACstGrammar(ACstGrammar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACstGrammar(ACstGrammar node)
    {
        inACstGrammar(node);
        if(node.getLitInt() != null)
        {
            node.getLitInt().apply(this);
        }
        outACstGrammar(node);
    }
}
