#!/bin/bash

# This code originated as a project for the COMP 520 class at McGill
# University in Winter 2015. Any subsequent COMP 520 student who is
# viewing this code must follow the course rules and report any viewing
# and/or use of the code.

if [[ $# == 0 ]]; then
	DIR=.
	ABS_DIR=`pwd`
elif [[ $# == 1 ]]; then
	DIR=$1
	ABS_DIR=`cd $1; pwd`
else
	echo "Usage: make_user_scripts.sh [target_directory]"
	exit 1
fi

echo "\
#!/bin/bash

# This file was generated by tools/make_user_scripts.sh

jarpath=\"$ABS_DIR/golite.jar\"

# Hybrid system: if this is a Cygwin installation where the Windows
# version of java is installed, we need to use a Windows-style path
if [[ \`which java\` =~ /cygdrive.* ]] && hash cygpath 2>/dev/null
then
	jarpath=\`cygpath -wl \"\$jarpath\"\`
fi

java -jar \"\$jarpath\" \$*
" > "$ABS_DIR/golite"

chmod u+x "$ABS_DIR/golite"

echo "Created $DIR/golite"

# If the Cygwin path utility is present then write a Windows batch
# script as well
if hash cygpath 2>/dev/null; then
	WINDOWS_DIR=`cygpath -wl "$ABS_DIR"`

	printf "\
@echo off\r
\r
rem This file was generated by tools/make_user_scripts.sh\r
\r
java -jar \"${WINDOWS_DIR//\\/\\\\}\\golite.jar\" %%*\r
" > "$ABS_DIR/golite.bat"

	echo "Created $WINDOWS_DIR\\golite.bat"
fi

