#!/usr/bin/bash

if [[ $# != 1 ]]; then
	echo "Usage: make_user_scripts.sh target_directory"
	exit 1
fi

ABSOLUTE_DIR=`cd $1; pwd`

echo "\
#!/bin/bash

# This file was generated by tools/make_user_scripts.sh

jarpath=\"$ABSOLUTE_DIR/golite.jar\"

# Hybrid system: if this is a Cygwin installation where the Windows
# version of java is installed, we need to use a Windows-style path
if [[ \`which java\` =~ /cygdrive.* ]] && hash cygpath 2>/dev/null
then
	jarpath=\`cygpath -wl \"\$jarpath\"\`
fi

java -jar \"\$jarpath\" \$*
" > "$1/golite"

chmod u+x "$1/golite"

# If the Cygwin path utility is present then write a Windows batch
# script as well
if hash cygpath 2>/dev/null; then
	WINDOWS_DIR=`cygpath -wl $1`

	printf "\
@echo off\r
\r
rem This file was generated by tools/make_user_scripts.sh\r
\r
java -jar \"$WINDOWS_DIR\\golite.jar\" %%*\r
" > "$1/golite.bat"
fi

